/**
 * ============================================
 * INTERVIEW SCHEDULING API
 * ============================================
 *
 * Typed client for the single interview scheduling API.
 *
 * Interview times are GENERATED by the backend from the central interview
 * configuration. Admins never create or modify slots.
 *
 * SECURITY NOTE: the backend is the authority for eligibility and availability.
 * Nothing here is trusted by the server - these calls are only for display.
 */

import { backendApiUrl } from "@/lib/client";

export type InterviewSlotStatus =
  | "available"
  | "already_taken"
  | "past";

export interface InterviewSlot {
  startAt: string;
  endAt: string;
  time: string;
  endTime: string;
  status: InterviewSlotStatus;
}

export interface InterviewConfig {
  timezone: string;
  interviewDurationMinutes: number;
  workingHours: {
    startHour: number;
    endHour: number;
  };
  allowedWeekdays: number[];
  schedulingHorizonDays: number;
  minLeadHours: number;
  mode: "online" | "onsite" | "phone";
  location: string;
}

export interface InterviewBooking {
  id: string;
  startAt: string;
  endAt: string;
  date: string;
  time: string;
  endTime: string;
  timezone: string;
  durationMinutes: number;
  status: string;
  mode: string;
  location: string;
  meetLink: string | null;
  bookedAt: string;
}

export interface InterviewConfigResponse {
  success: boolean;
  config: InterviewConfig;
  availableDates: string[];
  interviewEligible: boolean;
  eligibilityReason: string | null;
  eligibilityMessage: string;
  candidate: { id: string; name: string };
  existingBooking: InterviewBooking | null;
}

export interface AvailabilityResponse {
  success: boolean;
  date: string;
  timezone: string;
  interviewDurationMinutes: number;
  slots: InterviewSlot[];
}

export interface BookInterviewResponse {
  success: boolean;
  message: string;
  booking: InterviewBooking;
}

/**
 * Business error carrying the HTTP status and backend error code.
 */
export class InterviewApiError extends Error {
  status: number;
  code: string;

  constructor(status: number, message: string, code: string) {
    super(message);
    this.name = "InterviewApiError";
    this.status = status;
    this.code = code;
  }
}

/**
 * Turn a failed response into a message that is actually useful to a student.
 *
 * A 401 is NOT the same thing as a 403, and neither is the same as a 409.
 * Showing "Authentication required." for every failure was actively misleading:
 * it told an already-authenticated student that their session had expired when
 * in fact their project simply was not verified yet.
 */
function toApiError(status: number, data: Record<string, unknown>): InterviewApiError {
  const code = typeof data?.code === "string" ? data.code : "UNKNOWN";
  const serverMessage =
    typeof data?.message === "string" ? data.message : "";

  // 409: someone else took the time between our check and our submit.
  if (status === 409) {
    return new InterviewApiError(
      409,
      code === "INTERVIEW_ALREADY_BOOKED"
        ? "You already have an active interview scheduled."
        : "This interview time was just booked. Please select another time.",
      code
    );
  }

  // 401 / 403: the session is missing or invalid -> genuinely re-authenticate.
  if (status === 401 || (status === 403 && code === "UNAUTHORIZED")) {
    return new InterviewApiError(
      status,
      "Your session has expired. Please sign in again.",
      code
    );
  }

  // 403: authenticated, but not eligible. This is NOT an auth problem.
  if (status === 403) {
    return new InterviewApiError(
      403,
      serverMessage ||
        "Your project must be verified before scheduling an interview.",
      code
    );
  }

  return new InterviewApiError(
    status,
    serverMessage || "Unable to complete the request.",
    code
  );
}

async function call<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(backendApiUrl(path), {
    ...init,
    // Required for the HttpOnly candidate_session cookie to be sent.
    credentials: "include",
    headers: { "Content-Type": "application/json" },
    cache: "no-store",
  });

  const data = await response.json().catch(() => ({}));

  if (!response.ok) {
    throw toApiError(response.status, data);
  }

  return data as T;
}

export const interviewSchedulingService = {
  /**
   * Interview configuration + this student's eligibility.
   */
  getConfig(): Promise<InterviewConfigResponse> {
    return call<InterviewConfigResponse>("/api/student/interview/config");
  },

  /**
   * Generated interview times for a date, with booking state.
   *
   * Never includes the identity of whoever booked a time.
   */
  getAvailability(date: string): Promise<AvailabilityResponse> {
    return call<AvailabilityResponse>(
      `/api/student/interview/availability?date=${encodeURIComponent(date)}`
    );
  },

  /**
   * Book an interview. The backend performs all validation atomically.
   *
   * A race with another student surfaces as a 409
   * `INTERVIEW_TIME_ALREADY_BOOKED`.
   */
  book(startAt: string): Promise<BookInterviewResponse> {
    return call<BookInterviewResponse>("/api/student/interview/book", {
      method: "POST",
      body: JSON.stringify({ startAt }),
    });
  },

  /** The student's own active booking. */
  getBooking(): Promise<{ success: boolean; booking: InterviewBooking | null }> {
    return call("/api/student/interview/booking");
  },
};

// =====================================================
// ADMIN (READ-ONLY)
// =====================================================

export interface AdminScheduleEntry {
  startAt: string;
  endAt: string;
  time: string;
  endTime: string;
  status: "available" | "booked";
  booking: {
    id: string;
    status: string;
    bookedAt: string;
    candidate: {
      id: string | null;
      name: string | null;
      email: string | null;
      phone: string | null;
      role: string | null;
    };
    project: string | null;
    meetLink: string | null;
  } | null;
}

export interface AdminScheduleResponse {
  success: boolean;
  date: string;
  timezone: string;
  interviewDurationMinutes: number;
  mode: string;
  location: string;
  readOnly: boolean;
  formattedDate: string;
  serverTime: string;
  entries: AdminScheduleEntry[];
}

export const adminScheduleService = {
  /**
   * The generated schedule plus booking details for booked times.
   *
   * There is deliberately no create/edit/delete/assign counterpart anywhere in
   * this client: the admin schedule is read-only.
   */
  getSchedule(date: string): Promise<AdminScheduleResponse> {
    return call<AdminScheduleResponse>(
      `/api/admin/interviews/schedule?date=${encodeURIComponent(date)}`
    );
  },
};