/**
 * ============================================
 * INTERVIEW SLOTS (READ-ONLY)
 * ============================================
 *
 * Admins do NOT create, edit or delete interview slots. Interview times are
 * GENERATED by the system from the central interview configuration, and
 * bookings are created by students.
 *
 * All slot CRUD helpers were removed from this client. The read-only admin
 * schedule lives in `@/services/interviewScheduling.api` (adminScheduleService).
 *
 * For backward compatibility the types are retained, but the slot read path
 * now uses the generated interview availability endpoint.
 */

import { Slot } from "@/types";

export type { Slot };

export const slotService = {
  /**
   * Read-only access to generated interview times.
   *
   * NOTE: the legacy `/api/slots` endpoint never existed on the backend; this
   * method intentionally throws rather than silently returning bad data. Use
   * `interviewSchedulingService` instead.
   */
  async getSlots(): Promise<Slot[]> {
    throw new Error(
      "getSlots is no longer supported. Use interviewSchedulingService.getAvailability(date) for student times, or adminScheduleService.getSchedule(date) for the admin schedule."
    );
  },
};
