import express from "express";
import {
  getAvailableSlots,
  checkEligibility,
  detectConflicts,
  getSlotStatistics,
  slotHealthCheck
} from "./enhancedSlot.controller.js";

const router = express.Router();

/**
 * Middleware for candidate authentication
 */
const requireCandidate = (req, res, next) => {
  const candidateId = req.candidate?._id || req.headers['x-candidate-id'];

  if (!candidateId) {
    return res.status(401).json({
      success: false,
      error: "Candidate authentication required"
    });
  }

  req.candidateId = candidateId;
  next();
};

/**
 * Middleware for admin authentication
 *
 * NOTE: this router is READ-ONLY. Admins can never create, edit or delete
 * interview slots - interview times are generated by the system from the
 * central interview configuration. All write routes were removed.
 */
const requireAdmin = (req, res, next) => {
  const adminId = req.user?.id || req.headers['x-admin-id'];

  if (!adminId) {
    return res.status(401).json({
      success: false,
      error: "Admin authentication required"
    });
  }
  
  req.adminId = adminId;
  next();
};

/**
 * ============================================
 * PUBLIC READ-ONLY ENDPOINTS
 * ============================================
 */

// Health check
router.get("/health", slotHealthCheck);

// Get available slots (public, but role-based filtering)
router.get("/available", getAvailableSlots);

// Check eligibility (candidate-specific)
router.get("/:slotId/eligibility", checkEligibility);

// Detect conflicts before booking
router.post("/:slotId/conflicts", requireCandidate, detectConflicts);

/**
 * Read-only admin statistics.
 *
 * Slot creation, editing, deletion, availability changes and student
 * assignment are intentionally NOT exposed anywhere in the API. Bookings are
 * created by students via POST /api/student/interview/book.
 */
router.get("/statistics", requireAdmin, getSlotStatistics);

export default router;