import express from "express";

import { requireVerifiedSession } from "../../middleware/requireVerifiedSession.js";
import { requireAuth } from "../auth/auth.middleware.js";
import {
  BookingError,
  getAvailabilityForDate,
  getStudentBooking,
  bookInterview,
  getAdminSchedule,
} from "./interviewBooking.service.js";
import {
  getInterviewConfig,
  toPublicConfig,
  listSchedulableDates,
  isValidDateString,
  todayInTimezone,
  formatTimeInZone,
  formatDateInZone,
} from "./interviewConfig.service.js";
import { canBookInterviewSlot } from "../projects/deadline.service.js";

const router = express.Router();

/**
 * ============================================
 * INTERVIEW SCHEDULING
 * ============================================
 *
 * The interview schedule is GENERATED by the system from the central
 * interview configuration. Admins can VIEW the schedule but can NEVER create,
 * edit, delete or assign slots/bookings - there are no mutation endpoints here.
 */

/**
 * Resolve the requested date, defaulting to today in the config timezone.
 */
function resolveDate(query, timezone) {
  const requested = typeof query?.date === "string" ? query.date : "";

  if (!requested) {
    return { ok: true, date: todayInTimezone(timezone) };
  }

  if (!isValidDateString(requested)) {
    return {
      ok: false,
      message: "The provided date must be a valid YYYY-MM-DD value.",
    };
  }

  return { ok: true, date: requested };
}

/**
 * GET /api/student/interview/config
 *
 * Interview configuration plus the student's own eligibility, derived from the
 * PERSISTED verification state on the server.
 */
router.get(
  "/student/interview/config",
  requireVerifiedSession,
  async (req, res) => {
    try {
      const config = await getInterviewConfig();
      const eligibility = canBookInterviewSlot(req.candidate);
      const booking = await getStudentBooking(req.candidate._id, config);

      return res.status(200).json({
        success: true,
        config: toPublicConfig(config),
        availableDates: listSchedulableDates(config),
        interviewEligible: eligibility.eligible,
        eligibilityReason: eligibility.reason,
        eligibilityMessage: eligibility.message,
        candidate: {
          id: req.candidate._id,
          name: req.candidate.name,
        },
        existingBooking: booking,
      });
    } catch (error) {
      console.error("Error loading interview config:", error);
      return res
        .status(500)
        .json({ message: "Unable to load interview configuration." });
    }
  }
);

/**
 * GET /api/student/interview/availability?date=YYYY-MM-DD
 *
 * Returns the generated interview times for a date with their booking state.
 * A student NEVER sees who booked a time - only "available" / "already_taken".
 */
router.get(
  "/student/interview/availability",
  requireVerifiedSession,
  async (req, res) => {
    try {
      const config = await getInterviewConfig();
      const resolved = resolveDate(req.query, config.timezone);

      if (!resolved.ok) {
        return res.status(400).json({
          success: false,
          message: resolved.message,
          code: "INVALID_DATE",
        });
      }

      // Eligibility is enforced server-side. A rejected or unverified student
      // gets no schedule at all.
      const eligibility = canBookInterviewSlot(req.candidate);

      if (!eligibility.eligible && eligibility.reason !== "already_booked") {
        return res.status(403).json({
          success: false,
          message: eligibility.message,
          code: "INTERVIEW_NOT_ELIGIBLE",
          interviewEligible: false,
        });
      }

      const availability = await getAvailabilityForDate(
        config,
        req.candidate._id,
        resolved.date
      );

      return res.status(200).json({
        success: true,
        ...availability,
        interviewEligible: eligibility.eligible,
      });
    } catch (error) {
      console.error("Error loading availability:", error);
      return res
        .status(500)
        .json({ message: "Unable to load interview availability." });
    }
  }
);

/**
 * POST /api/student/interview/book
 *
 * Body: { "startAt": "2026-10-08T10:30:00+05:30" }
 *
 * The backend performs the complete validation and the booking is a single
 * atomic insert protected by a unique index, so two simultaneous requests can
 * never both succeed.
 */
router.post(
  "/student/interview/book",
  requireVerifiedSession,
  async (req, res) => {
    try {
      const config = await getInterviewConfig();

      const rawStartAt = req.body?.startAt;

      if (typeof rawStartAt !== "string" || !rawStartAt) {
        return res.status(400).json({
          success: false,
          message: "startAt is required.",
          code: "INVALID_START_AT",
        });
      }

      const startAt = new Date(rawStartAt);

      if (Number.isNaN(startAt.getTime())) {
        return res.status(400).json({
          success: false,
          message: "The provided startAt is not a valid date and time.",
          code: "INVALID_START_AT",
        });
      }

      const booking = await bookInterview({
        config,
        candidate: req.candidate,
        startAt,
      });

      return res.status(201).json({
        success: true,
        message: "Interview scheduled successfully.",
        booking,
      });
    } catch (error) {
      if (error instanceof BookingError) {
        return res.status(error.status).json({
          success: false,
          message: error.message,
          code: error.code,
        });
      }

      console.error("Error booking interview:", error);
      return res
        .status(500)
        .json({ message: "Unable to book the interview." });
    }
  }
);

/**
 * GET /api/student/interview/booking
 *
 * The candidate's own active booking only.
 */
router.get(
  "/student/interview/booking",
  requireVerifiedSession,
  async (req, res) => {
    try {
      const config = await getInterviewConfig();
      const booking = await getStudentBooking(req.candidate._id, config);

      return res.status(200).json({
        success: true,
        booking: booking || null,
      });
    } catch (error) {
      console.error("Error loading booking:", error);
      return res.status(500).json({ message: "Unable to load booking." });
    }
  }
);

/**
 * GET /api/admin/interviews/schedule?date=YYYY-MM-DD
 *
 * ADMIN ONLY, READ-ONLY. Returns the generated schedule plus student details
 * for booked times. There is deliberately no mutation counterpart.
 */
router.get(
  "/admin/interviews/schedule",
  requireAuth,
  async (req, res) => {
    try {
      const config = await getInterviewConfig();
      const resolved = resolveDate(req.query, config.timezone);

      if (!resolved.ok) {
        return res.status(400).json({
          success: false,
          message: resolved.message,
          code: "INVALID_DATE",
        });
      }

      const schedule = await getAdminSchedule(config, resolved.date);

      return res.status(200).json({
        success: true,
        ...schedule,
        formattedDate: formatDateInZone(
          new Date(`${schedule.date}T00:00:00Z`),
          "UTC"
        ),
        serverTime: formatTimeInZone(new Date(), config.timezone),
      });
    } catch (error) {
      console.error("Error loading admin schedule:", error);
      return res
        .status(500)
        .json({ message: "Unable to load the interview schedule." });
    }
  }
);

export default router;