import mongoose from "mongoose";

/**
 * =====================================================
 * INTERVIEW CONFIGURATION (CENTRAL, SYSTEM-OWNED)
 * =====================================================
 *
 * The interview schedule is GENERATED by the system. There is deliberately
 * NO admin-managed slot list and NO admin UI that edits this configuration.
 * These values are the single source of truth used to generate every possible
 * interview time.
 *
 * Defaults are derived from the pre-existing scheduling configuration
 * (SlotTemplate.timeRange / Slot.timezone defaults) so behaviour is preserved.
 *
 * Timezone: "Asia/Kolkata" (matches the existing Slot model default).
 */

const interviewConfigSchema = new mongoose.Schema(
  {
    key: {
      type: String,
      required: true,
      unique: true,
      default: "default",
      immutable: true,
      comment: "Singleton key. Only one configuration document exists.",
    },

    // -------------------------------------------------
    // INTERVIEW LENGTH
    // -------------------------------------------------
    interviewDurationMinutes: {
      type: Number,
      required: true,
      default: 30,
      min: 15,
      max: 480,
      comment: "Duration of a single interview, in minutes.",
    },

    // -------------------------------------------------
    // TIMEZONE
    // -------------------------------------------------
    timezone: {
      type: String,
      required: true,
      default: "Asia/Kolkata",
      comment: "IANA timezone all interview times are expressed in.",
    },

    // -------------------------------------------------
    // WORKING HOURS (local wall-clock time in `timezone`)
    // -------------------------------------------------
    workingHours: {
      startHour: {
        type: Number,
        default: 9,
        min: 0,
        max: 23,
      },
      endHour: {
        type: Number,
        default: 18,
        min: 1,
        max: 24,
      },
    },

    // -------------------------------------------------
    // ALLOWED DAYS (0 = Sunday ... 6 = Saturday)
    // -------------------------------------------------
    allowedWeekdays: {
      type: [Number],
      default: [1, 2, 3, 4, 5],
      validate: {
        validator: (days) =>
          Array.isArray(days) &&
          days.length > 0 &&
          days.every((day) => Number.isInteger(day) && day >= 0 && day <= 6),
        message: "allowedWeekdays must be a non-empty array of 0-6",
      },
    },

    // -------------------------------------------------
    // SCHEDULING WINDOW
    // -------------------------------------------------
    schedulingHorizonDays: {
      type: Number,
      default: 30,
      min: 1,
      max: 365,
      comment: "How many days ahead a student may book.",
    },

    minLeadHours: {
      type: Number,
      default: 2,
      min: 0,
      max: 168,
      comment: "Minimum hours between now and the interview start.",
    },

    // -------------------------------------------------
    // INTERVIEW MODE
    // -------------------------------------------------
    mode: {
      type: String,
      enum: ["online", "onsite", "phone"],
      default: "online",
    },

    location: {
      type: String,
      default: "Online",
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

/**
 * Remove any mutator paths. The schedule is system-generated, so this
 * document is configuration only and is never exposed through a
 * write endpoint.
 */
interviewConfigSchema.pre("save", function (next) {
  if (!this.isNew) {
    return next(new Error("Interview configuration is immutable."));
  }
  next();
});

const InterviewConfig = mongoose.model(
  "InterviewConfig",
  interviewConfigSchema
);

export default InterviewConfig;