import InterviewConfig from "./interviewConfig.model.js";

/**
 * =====================================================
 * INTERVIEW CONFIGURATION SERVICE
 * =====================================================
 *
 * Central scheduling configuration. There is intentionally no write endpoint:
 * the interview schedule is generated by the system and is NOT admin-managed.
 */

const SINGLETON_KEY = "default";

/**
 * Load (and lazily seed) the singleton interview configuration.
 */
export async function getInterviewConfig() {
  let config = await InterviewConfig.findOne({ key: SINGLETON_KEY });

  if (!config) {
    try {
      config = await InterviewConfig.create({
        key: SINGLETON_KEY,
        workingHours: { startHour: 0, endHour: 24 },
        minLeadHours: 0,
      });
    } catch (error) {
      // Lost a create race - another request seeded it first.
      config = await InterviewConfig.findOne({ key: SINGLETON_KEY });
      if (!config) throw error;
    }
  }

  // Ensure un-restricted schedule rules (no 2-hour minimum lead, no 9-18 business hours restriction)
  if (
    config &&
    (config.minLeadHours !== 0 ||
      config.workingHours?.startHour !== 0 ||
      config.workingHours?.endHour !== 24)
  ) {
    config.minLeadHours = 0;
    config.workingHours = { startHour: 0, endHour: 24 };
    if (typeof config.save === "function") {
      await config.save().catch(() => {});
    }
  }

  return config;
}

/**
 * Plain-object view of the configuration (safe to serialise to clients).
 */
export function toPublicConfig(config) {
  return {
    timezone: config.timezone,
    interviewDurationMinutes: config.interviewDurationMinutes,
    workingHours: {
      startHour: config.workingHours.startHour,
      endHour: config.workingHours.endHour,
    },
    allowedWeekdays: [...config.allowedWeekdays],
    schedulingHorizonDays: config.schedulingHorizonDays,
    minLeadHours: config.minLeadHours,
    mode: config.mode,
    location: config.location,
  };
}

// =====================================================
// TIMEZONE HELPERS
// =====================================================

/**
 * Offset (in minutes) between UTC and `timezone` at the given instant.
 * Uses Intl, so it is correct for any IANA zone including DST transitions.
 */
function getTimezoneOffsetMinutes(date, timezone) {
  const dtf = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    hour12: false,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  });

  const parts = dtf.formatToParts(date).reduce((acc, part) => {
    acc[part.type] = part.value;
    return acc;
  }, {});

  const asUTC = Date.UTC(
    Number(parts.year),
    Number(parts.month) - 1,
    Number(parts.day),
    Number(parts.hour === "24" ? "00" : parts.hour),
    Number(parts.minute),
    Number(parts.second)
  );

  return (asUTC - date.getTime()) / 60000;
}

/**
 * Convert a LOCAL wall-clock date + time in `timezone` into a real UTC Date.
 *
 * Two-pass: guess with the offset at the naive instant, then correct with the
 * offset actually in effect at the guessed instant. This resolves DST
 * transitions correctly for both gaps and overlaps.
 *
 * @param {string} dateStr "YYYY-MM-DD"
 * @param {number} hour 0-23
 * @param {number} minute 0-59
 * @param {string} timezone IANA timezone
 * @returns {Date}
 */
export function zonedWallClockToUtc(dateStr, hour, minute, timezone) {
  const [year, month, day] = String(dateStr)
    .split("-")
    .map((part) => Number(part));

  const naive = Date.UTC(year, month - 1, day, hour, minute, 0);

  let utcGuess =
    naive - getTimezoneOffsetMinutes(new Date(naive), timezone) * 60000;
  utcGuess =
    naive - getTimezoneOffsetMinutes(new Date(utcGuess), timezone) * 60000;

  return new Date(utcGuess);
}

const WEEKDAY_ORDER = ["sun", "mon", "tue", "wed", "thu", "fri", "sat"];

/**
 * Weekday (0=Sunday..6=Saturday) of a "YYYY-MM-DD" string interpreted in
 * `timezone` at midday (midday never shifts across a day boundary).
 */
export function getWeekdayForDate(dateStr, timezone) {
  const noon = zonedWallClockToUtc(dateStr, 12, 0, timezone);

  const short = new Intl.DateTimeFormat("en-US", {
    timeZone: timezone,
    weekday: "short",
  })
    .format(noon)
    .toLowerCase();

  const index = WEEKDAY_ORDER.indexOf(short);
  return index === -1 ? noon.getUTCDay() : index;
}

/**
 * Validate a "YYYY-MM-DD" string (rejects impossible dates like 2026-02-30).
 */
export function isValidDateString(value) {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return false;
  }

  const [year, month, day] = value.split("-").map(Number);
  const probe = new Date(Date.UTC(year, month - 1, day));

  return (
    probe.getUTCFullYear() === year &&
    probe.getUTCMonth() === month - 1 &&
    probe.getUTCDate() === day
  );
}

/**
 * Today's date string ("YYYY-MM-DD") in `timezone`.
 */
export function todayInTimezone(timezone) {
  return new Intl.DateTimeFormat("en-CA", {
    timeZone: timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());
}

/**
 * Shift a "YYYY-MM-DD" string by whole days (calendar math, not ms math).
 */
export function addDaysToDateString(dateStr, days) {
  const [year, month, day] = dateStr.split("-").map(Number);
  const shifted = new Date(Date.UTC(year, month - 1, day + days));
  return shifted.toISOString().slice(0, 10);
}

/**
 * =====================================================
 * TIME GENERATION
 * =====================================================
 */

/**
 * Generate every possible interview start time for a given local date,
 * derived purely from the system configuration.
 *
 * No admin pre-created slots are involved. Returns normalized UTC Dates so all
 * downstream comparisons are timestamp based, never string based.
 *
 * @returns {Array<{startAt: Date, endAt: Date}>}
 */
export function generateInterviewTimesForDate(config, dateStr) {
  if (!isValidDateString(dateStr)) {
    return [];
  }

  const { timezone, interviewDurationMinutes } = config;

  if (!config.allowedWeekdays.includes(getWeekdayForDate(dateStr, timezone))) {
    return [];
  }

  const { startHour, endHour } = config.workingHours;

  // The interview must finish at or before endHour on the same local day.
  const windowStartMinutes = startHour * 60;
  const windowEndMinutes = endHour * 60;

  const times = [];

  for (
    let minuteOfDay = windowStartMinutes;
    minuteOfDay + interviewDurationMinutes <= windowEndMinutes;
    minuteOfDay += interviewDurationMinutes
  ) {
    const hour = Math.floor(minuteOfDay / 60);
    const minute = minuteOfDay % 60;

    const startAt = zonedWallClockToUtc(dateStr, hour, minute, timezone);
    const endAt = new Date(
      startAt.getTime() + interviewDurationMinutes * 60000
    );

    times.push({ startAt, endAt });
  }

  return times;
}

/**
 * Every date the system can currently schedule, within the booking horizon.
 *
 * @returns {string[]} "YYYY-MM-DD" strings in the config timezone
 */
export function listSchedulableDates(config) {
  const today = todayInTimezone(config.timezone);
  const dates = [];

  for (let offset = 0; offset <= config.schedulingHorizonDays; offset += 1) {
    const candidate = addDaysToDateString(today, offset);

    if (
      config.allowedWeekdays.includes(
        getWeekdayForDate(candidate, config.timezone)
      )
    ) {
      dates.push(candidate);
    }
  }

  return dates;
}

/**
 * =====================================================
 * BOOKING VALIDATION
 * =====================================================
 */

/**
 * Validate a candidate-chosen start instant against the scheduling
 * configuration and the generated time list.
 *
 * @param {object} config InterviewConfig document
 * @param {Date} startAt Normalized booking instant
 * @param {Date} now Injected for testability
 * @returns {{valid: boolean, code?: string, message?: string, endAt?: Date}}
 */
export function validateStartInstant(config, startAt, now = new Date()) {
  if (!(startAt instanceof Date) || Number.isNaN(startAt.getTime())) {
    return {
      valid: false,
      code: "INVALID_START_AT",
      message: "The selected interview time is not a valid date and time.",
    };
  }

  // Work out which local calendar day this instant belongs to, then confirm
  // the instant is one of the times the system actually generates.
  const localDate = new Intl.DateTimeFormat("en-CA", {
    timeZone: config.timezone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(startAt);

  const generated = generateInterviewTimesForDate(config, localDate);

  const match = generated.find(
    (slot) => slot.startAt.getTime() === startAt.getTime()
  );

  if (!match) {
    return {
      valid: false,
      code: "INVALID_INTERVIEW_TIME",
      message:
        "The selected time is not an available interview time. Please choose one of the listed times.",
    };
  }

  // Past check, based on the real timestamp.
  if (startAt.getTime() <= now.getTime()) {
    return {
      valid: false,
      code: "INTERVIEW_TIME_IN_PAST",
      message: "The selected interview time is in the past.",
    };
  }

  // Booking window checks.
  const horizonEnd = addDaysToDateString(
    todayInTimezone(config.timezone),
    config.schedulingHorizonDays
  );

  if (localDate > horizonEnd) {
    return {
      valid: false,
      code: "OUT_OF_RANGE",
      message: `Interviews can only be booked up to ${config.schedulingHorizonDays} days in advance.`,
    };
  }

  // Minimum advance-selection restriction removed:
  // Any genuine future slot is valid (past check already enforced above).
  if (config.minLeadHours && config.minLeadHours > 0) {
    const leadMs = startAt.getTime() - now.getTime();
    if (leadMs < config.minLeadHours * 3600000) {
      return {
        valid: false,
        code: "INSUFFICIENT_LEAD_TIME",
        message: `Interviews must be booked at least ${config.minLeadHours} hours in advance.`,
      };
    }
  }

  return { valid: true, endAt: match.endAt };
}

// =====================================================
// FORMATTING
// =====================================================

export function formatTimeInZone(date, timezone) {
  return new Intl.DateTimeFormat("en-IN", {
    timeZone: timezone,
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  }).format(date);
}

export function formatDateInZone(date, timezone) {
  return new Intl.DateTimeFormat("en-IN", {
    timeZone: timezone,
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date);
}

export { SINGLETON_KEY };