import express from "express";

const router = express.Router();

/**
 * ============================================
 * LEGACY SLOT ROUTES - RETIRED
 * ============================================
 *
 * Interview times are now GENERATED by the system from the central interview
 * configuration and booked through the interview booking API. Admins do not
 * create, edit or delete slots, so there is no admin-managed slot list.
 *
 * The endpoints below used to be:
 *   GET  /api/student/slots
 *   POST /api/student/book-slot
 *   GET  /api/student/booked-slot
 *
 * They were removed to guarantee there is exactly ONE interview scheduling
 * system. Clients must use:
 *   GET  /api/student/interview/config
 *   GET  /api/student/interview/availability?date=YYYY-MM-DD
 *   POST /api/student/interview/book
 *   GET  /api/student/interview/booking
 *
 * Each returns a controlled 410 with a pointer to the replacement, so any
 * stale client fails loudly instead of silently losing data.
 */

const RETIRED_MESSAGE =
  "This legacy interview slot endpoint has been retired. " +
  "Interview times are now generated by the system. " +
  "Use /api/student/interview/availability, /api/student/interview/book " +
  "and /api/student/interview/booking instead.";

const retired = (req, res) =>
  res.status(410).json({
    success: false,
    code: "ENDPOINT_RETIRED",
    message: RETIRED_MESSAGE,
    replacements: {
      config: "/api/student/interview/config",
      availability: "/api/student/interview/availability",
      book: "/api/student/interview/book",
      booking: "/api/student/interview/booking",
    },
  });

router.get("/student/slots", retired);
router.post("/student/book-slot", retired);
router.post("/student/book", retired);
router.get("/student/booked-slot", retired);

export default router;