import { redirect } from "next/navigation";

/**
 * This page previously rendered admin-managed interview slots.
 *
 * Interview times are now GENERATED by the system and booked through the
 * interview scheduling API, so the student scheduling experience lives at
 * /student/interview-scheduling.
 */
export default function BookSlotRedirectPage() {
  redirect("/student/interview-scheduling");
}
