"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { ChevronLeft, ChevronRight, Search } from "lucide-react";

import {
  adminScheduleService,
  AdminScheduleEntry,
  AdminScheduleResponse,
} from "@/services/interviewScheduling.api";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Skeleton } from "@/components/ui/Skeleton";
import { ErrorState } from "@/components/ui/ErrorState";
import { cn } from "@/lib/utils";

/**
 * ============================================
 * ADMIN INTERVIEW SCHEDULE (READ-ONLY)
 * ============================================
 *
 * Interview times are GENERATED by the system from the central interview
 * configuration, and bookings are created by STUDENTS.
 *
 * There are deliberately NO mutation controls on this page:
 *   - no Create Slot
 *   - no Edit / Delete Slot
 *   - no Change Time / Change Date
 *   - no Mark Available / Unavailable
 *   - no Assign Student / Manually Book
 *
 * The backend exposes no corresponding mutation endpoints either.
 */

function toKey(date: Date) {
  return new Date(
    Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate())
  )
    .toISOString()
    .slice(0, 10);
}

function shiftDate(dateStr: string, days: number) {
  const [year, month, day] = dateStr.split("-").map(Number);
  const shifted = new Date(Date.UTC(year, month - 1, day + days));

  return `${shifted.getUTCFullYear()}-${String(shifted.getUTCMonth() + 1).padStart(2, "0")}-${String(shifted.getUTCDate()).padStart(2, "0")}`;
}

function formatDateLabel(dateStr: string) {
  return new Date(`${dateStr}T00:00:00Z`).toLocaleDateString("en-IN", {
    weekday: "long",
    day: "numeric",
    month: "long",
    year: "numeric",
    timeZone: "UTC",
  });
}

function capitalize(value: string) {
  return value ? value.charAt(0).toUpperCase() + value.slice(1) : "—";
}

export default function SchedulePage() {
  const [selectedDate, setSelectedDate] = useState<string>(() =>
    toKey(new Date())
  );
  const [schedule, setSchedule] = useState<AdminScheduleResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);
  const [query, setQuery] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError(false);

    try {
      const data = await adminScheduleService.getSchedule(selectedDate);
      setSchedule(data);
    } catch {
      setError(true);
    } finally {
      setLoading(false);
    }
  }, [selectedDate]);

  useEffect(() => {
    load();
  }, [load]);

  const navigate = (direction: -1 | 1) => {
    setSelectedDate((current) => shiftDate(current, direction));
  };

  /**
   * Optional filter across BOOKED entries only - an available entry has no
   * student to search against.
   */
  const entries = useMemo<AdminScheduleEntry[]>(() => {
    const all = schedule?.entries ?? [];

    if (!query.trim()) return all;

    const needle = query.trim().toLowerCase();

    return all.filter((entry) => {
      if (!entry.booking) return false;

      const { candidate, project } = entry.booking;

      return [
        candidate.name,
        candidate.email,
        candidate.phone,
        candidate.role,
        project,
      ]
        .filter(Boolean)
        .some((value) => String(value).toLowerCase().includes(needle));
    });
  }, [schedule, query]);

  const bookedCount = entries.filter((entry) => entry.status === "booked").length;
  const availableCount = entries.length - bookedCount;

  return (
    <div className="space-y-6">
      {/* --------------------------------------------------------- */}
      {/* HEADER                                                     */}
      {/* --------------------------------------------------------- */}

      <div className="flex flex-col gap-1">
        <h1 className="text-xl font-bold tracking-tight text-slate-900 dark:text-white">
          Interview Schedule
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400">
          Read-only view. Interview times are generated by the system and booked
          by students.
        </p>
      </div>

      {/* --------------------------------------------------------- */}
      {/* DATE NAVIGATION                                            */}
      {/* --------------------------------------------------------- */}

      <Card>
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-3.5 dark:border-white/5">
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="ghost"
              onClick={() => navigate(-1)}
              aria-label="Previous day"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>

            <span className="min-w-[200px] text-sm font-semibold text-slate-900 dark:text-white">
              {formatDateLabel(selectedDate)}
            </span>

            <Button
              size="sm"
              variant="ghost"
              onClick={() => navigate(1)}
              aria-label="Next day"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>

            <Button
              size="sm"
              variant="ghost"
              onClick={() => setSelectedDate(toKey(new Date()))}
            >
              Today
            </Button>
          </div>

          <div className="relative">
            <Search className="pointer-events-none absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />
            <input
              type="search"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search student, email, project…"
              aria-label="Search booked students"
              className="w-64 rounded-md border border-slate-200 bg-white py-1.5 pl-8 pr-3 text-sm text-slate-700 outline-none focus:border-accent-400 dark:border-white/10 dark:bg-white/5 dark:text-slate-200"
            />
          </div>
        </div>

        {/* Schedule configuration (read-only) */}
        {schedule && (
          <div className="flex flex-wrap items-center gap-x-6 gap-y-2 px-5 py-3 text-xs text-slate-500 dark:text-slate-400">
            <span>
              Timezone:{" "}
              <strong className="font-medium text-slate-700 dark:text-slate-200">
                {schedule.timezone}
              </strong>
            </span>
            <span>
              Duration:{" "}
              <strong className="font-medium text-slate-700 dark:text-slate-200">
                {schedule.interviewDurationMinutes} minutes
              </strong>
            </span>
            <span>
              Mode:{" "}
              <strong className="font-medium text-slate-700 dark:text-slate-200">
                {schedule.mode}
              </strong>
            </span>
            <span>
              Booked:{" "}
              <strong className="font-medium text-slate-700 dark:text-slate-200">
                {bookedCount}
              </strong>
            </span>
            <span>
              Available:{" "}
              <strong className="font-medium text-slate-700 dark:text-slate-200">
                {availableCount}
              </strong>
            </span>
          </div>
        )}

        <div className="flex items-center gap-4 border-t border-slate-100 px-5 py-2.5 text-xs text-slate-500 dark:border-white/5 dark:text-slate-400">
          <span className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-emerald-500" />
            Available
          </span>
          <span className="flex items-center gap-1.5">
            <span className="h-2 w-2 rounded-full bg-red-500" />
            Booked
          </span>
        </div>
      </Card>

      {/* --------------------------------------------------------- */}
      {/* SCHEDULE ENTRIES                                           */}
      {/* --------------------------------------------------------- */}

      {loading ? (
        <Card>
          <div className="space-y-3 p-5">
            <Skeleton className="h-16 w-full" />
            <Skeleton className="h-16 w-full" />
            <Skeleton className="h-16 w-full" />
          </div>
        </Card>
      ) : error ? (
        <ErrorState onRetry={load} />
      ) : entries.length === 0 ? (
        <Card>
          <div className="p-8 text-center text-sm text-slate-500">
            {query.trim()
              ? "No booked interviews match your search."
              : "No interview times are scheduled for this date."}
          </div>
        </Card>
      ) : (
        <Card>
          <ul className="divide-y divide-slate-100 dark:divide-white/5">
            {entries.map((entry) => (
              <li
                key={entry.startAt}
                className={cn(
                  "px-5 py-4",
                  entry.status === "booked" && "bg-red-50/40 dark:bg-red-500/5"
                )}
              >
                <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                  {/* Time + status */}
                  <div className="flex items-center gap-3 sm:w-40">
                    <span
                      aria-hidden
                      className={cn(
                        "h-2.5 w-2.5 shrink-0 rounded-full",
                        entry.status === "booked"
                          ? "bg-red-500"
                          : "bg-emerald-500"
                      )}
                    />
                    <div>
                      <p className="text-sm font-semibold text-slate-900 dark:text-white">
                        {entry.time}
                      </p>
                      <p className="text-xs text-slate-500">
                        {entry.status === "booked"
                          ? "🔴 Booked"
                          : "🟢 Available"}
                      </p>
                    </div>
                  </div>

                  {/* Student details (visible to admins only) */}
                  {entry.booking ? (
                    <dl className="grid flex-1 gap-x-8 gap-y-2 text-sm sm:grid-cols-2 lg:grid-cols-4">
                      <Detail
                        label="Student"
                        value={entry.booking.candidate.name}
                      />
                      <Detail
                        label="Email"
                        value={entry.booking.candidate.email}
                      />
                      <Detail
                        label="Phone"
                        value={entry.booking.candidate.phone}
                      />
                      <Detail
                        label="Project"
                        value={entry.booking.project}
                      />
                      <Detail
                        label="Role"
                        value={entry.booking.candidate.role}
                      />
                      <Detail
                        label="Interview date"
                        value={formatDateLabel(selectedDate)}
                      />
                      <Detail
                        label="Interview time"
                        value={entry.time}
                      />
                      <Detail
                        label="Status"
                        value={capitalize(entry.booking.status)}
                      />
                      <Detail
                        label="Booked at"
                        value={new Date(entry.booking.bookedAt).toLocaleString(
                          "en-IN",
                          { timeZone: schedule?.timezone }
                        )}
                      />
                      {entry.booking.meetLink && (
                        <div className="min-w-0 sm:col-span-2">
                          <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
                            Google Meet
                          </dt>
                          <dd className="mt-0.5 truncate text-sm font-medium text-indigo-600 dark:text-indigo-400">
                            <a
                              href={entry.booking.meetLink}
                              target="_blank"
                              rel="noreferrer"
                              className="hover:underline"
                            >
                              {entry.booking.meetLink}
                            </a>
                          </dd>
                        </div>
                      )}
                    </dl>
                  ) : (
                    <p className="flex-1 text-sm text-slate-400">
                      No candidate booked this time.
                    </p>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Card>
      )}
    </div>
  );
}

function Detail({ label, value }: { label: string; value?: string | null }) {
  return (
    <div className="min-w-0">
      <dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-400">
        {label}
      </dt>
      <dd className="mt-0.5 break-words text-sm text-slate-900 dark:text-slate-100">
        {value || "—"}
      </dd>
    </div>
  );
}